import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { createPinia, setActivePinia } from 'pinia'
import { useUpdaterStore } from './updater'
import { useMqttStore } from './mqtt'
import { effectScope, ref } from 'vue'
import { useUpdateProtection } from '@/composables/useUpdateProtection'

const native = vi.hoisted(() => ({ check: vi.fn(), download: vi.fn(), install: vi.fn(), close: vi.fn(), relaunch: vi.fn(), message: vi.fn(), confirm: vi.fn(), flush: vi.fn() }))
vi.mock('element-plus', () => ({ ElMessage: { success: native.message, error: native.message }, ElMessageBox: { confirm: native.confirm } }))
vi.mock('@/utils/errorLogBuffer', () => ({ errorLogBuffer: { flush: native.flush } }))
vi.mock('@tauri-apps/plugin-updater', () => ({ check: native.check }))
vi.mock('@tauri-apps/plugin-process', () => ({ relaunch: native.relaunch }))
vi.mock('@tauri-apps/api/app', () => ({ getVersion: async () => '1.8.1' }))

beforeEach(() => {
  vi.resetAllMocks()
  vi.useFakeTimers()
  localStorage.clear()
  setActivePinia(createPinia())
  native.check.mockResolvedValue(null)
  native.close.mockResolvedValue(undefined)
  vi.spyOn(console, 'error').mockImplementation(() => {})
})

it('shares a pending startup check with manual callers and reports its result', async () => {
  let finish!: (value: null) => void
  native.check.mockReturnValue(new Promise(resolve => { finish = resolve }))
  const updater = useUpdaterStore()
  const automatic = updater.check()
  await Promise.resolve()
  const manual = updater.check({ interactive: true })
  finish(null)
  await Promise.all([automatic, manual])
  expect(native.check).toHaveBeenCalledTimes(1)
  expect(native.message).toHaveBeenCalled()
})
afterEach(() => { vi.useRealTimers(); vi.restoreAllMocks() })

it('delays the startup check eight seconds and persists the daily throttle across restarts', async () => {
  const updater = useUpdaterStore()
  updater.initialize()
  await vi.advanceTimersByTimeAsync(7999)
  expect(native.check).not.toHaveBeenCalled()
  await vi.advanceTimersByTimeAsync(1)
  expect(updater.phase).toBe('up_to_date')
  await updater.dispose()
  setActivePinia(createPinia())
  useUpdaterStore().initialize()
  await vi.advanceTimersByTimeAsync(8000)
  expect(native.check).toHaveBeenCalledTimes(1)
})

it('downloads once in the background, exposes progress, and never installs on completion', async () => {
  native.check.mockResolvedValue({ version: '1.9.0', currentVersion: '1.8.1', download: native.download, close: native.close })
  let finish!: () => void
  native.download.mockImplementation(callback => {
    callback({ event: 'Started', data: { contentLength: 100 } })
    callback({ event: 'Progress', data: { chunkLength: 40 } })
    return new Promise<void>(resolve => { finish = resolve })
  })
  const updater = useUpdaterStore()
  await updater.check()
  expect(updater.progress).toBe(40)
  const joined = updater.download()
  finish()
  await joined
  expect(updater.phase).toBe('ready')
  expect(native.download).toHaveBeenCalledTimes(1)
  expect(native.install).not.toHaveBeenCalled()
  expect(native.relaunch).not.toHaveBeenCalled()
})

it('skips a downloading version immediately but closes its resource only after download settles', async () => {
  native.check.mockResolvedValue({ version: '1.9.0', download: native.download, close: native.close })
  let finish!: () => void
  let progress!: (event: unknown) => void
  native.download.mockImplementation(callback => {
    progress = callback
    return new Promise<void>(resolve => { finish = resolve })
  })
  const updater = useUpdaterStore()
  await updater.check()
  const skipping = updater.skipVersion()
  expect(updater.info).toBeNull()
  expect(native.close).not.toHaveBeenCalled()
  progress({ event: 'Progress', data: { chunkLength: 500 } })
  finish()
  await skipping
  expect(updater.phase).toBe('idle')
  expect(updater.progress).toBeNull()
  expect(native.close).toHaveBeenCalledTimes(1)
  expect(updater.skippedVersion).toBe('1.9.0')
})

it.each([true, false])('accurately reports a persisted skipped release without downloading it (interactive=%s)', async interactive => {
  localStorage.setItem('mqtt-client-update-skipped-version', '1.9.0')
  native.check.mockResolvedValueOnce({ version: '1.9.0', date: '2026-10-10', body: 'Skipped release notes', download: native.download, install: native.install, close: native.close })
  const updater = useUpdaterStore()
  const result = await updater.check({ interactive })
  expect(result).toEqual({ hasUpdate: false, latestVersion: 'v1.9.0', currentVersion: '1.8.1', date: '2026-10-10', body: 'Skipped release notes' })
  expect(updater.phase).toBe('skipped')
  expect(updater.skippedVersion).toBe('1.9.0')
  expect(localStorage.getItem('mqtt-client-update-skipped-version')).toBe('1.9.0')
  expect(updater.canDownload).toBe(false)
  expect(updater.canInstall).toBe(false)
  expect(await updater.download()).toBe(false)
  expect(await updater.install()).toBe(false)
  expect(native.download).not.toHaveBeenCalled()
  expect(native.install).not.toHaveBeenCalled()
  expect(native.relaunch).not.toHaveBeenCalled()
  if (interactive) expect(native.message).toHaveBeenCalledExactlyOnceWith('Version v1.9.0 is available but you skipped it')
  else expect(native.message).not.toHaveBeenCalled()
  await updater.dispose()
  expect(native.close).toHaveBeenCalledOnce()
})

it('offers a newer release after finding a persisted skipped version', async () => {
  localStorage.setItem('mqtt-client-update-skipped-version', '1.9.0')
  const closeNew = vi.fn().mockResolvedValue(undefined)
  native.check.mockResolvedValueOnce({ version: '1.9.0', download: native.download, close: native.close })
    .mockResolvedValueOnce({ version: '2.0.0', download: native.download, close: closeNew })
  const updater = useUpdaterStore()
  updater.setPreferences({ autoCheck: true, autoDownload: false })
  await updater.check()
  await updater.check({ interactive: true })
  expect(updater.phase).toBe('available')
  expect(updater.info?.latestVersion).toBe('v2.0.0')
  expect(updater.canDownload).toBe(true)
  expect(updater.skippedVersion).toBe('1.9.0')
  expect(native.close).toHaveBeenCalledOnce()
  expect(closeNew).not.toHaveBeenCalled()
  await updater.dispose()
  expect(closeNew).toHaveBeenCalledOnce()
})

it('keeps another downloaded release consistent when a recheck finds a skipped release', async () => {
  localStorage.setItem('mqtt-client-update-skipped-version', '1.9.0')
  const closeSkipped = vi.fn().mockResolvedValue(undefined)
  native.check.mockResolvedValueOnce({ version: '2.0.0', download: native.download, close: native.close })
    .mockResolvedValueOnce({ version: '1.9.0', download: native.download, close: closeSkipped })
  const updater = useUpdaterStore()
  await updater.check()
  await updater.download()
  expect(updater.canInstall).toBe(true)
  await updater.check({ interactive: true })
  expect(updater.phase).toBe('skipped')
  expect(updater.info?.latestVersion).toBe('v1.9.0')
  expect(updater.canInstall).toBe(false)
  expect(updater.canDownload).toBe(false)
  expect(updater.progress).toBeNull()
  expect(native.download).toHaveBeenCalledOnce()
  await updater.dispose()
  expect(native.close).toHaveBeenCalledOnce()
  expect(closeSkipped).toHaveBeenCalledOnce()
})

it('public installation allows later and rechecks new connections after log flushing before installation', async () => {
  native.check.mockResolvedValue({ version: '1.9.0', download: native.download, install: native.install, close: native.close })
  const updater = useUpdaterStore()
  await updater.check()
  await updater.download()
  native.confirm.mockRejectedValueOnce('cancel')
  expect(await updater.install()).toBe(false)
  expect(native.install).not.toHaveBeenCalled()
  native.confirm.mockResolvedValueOnce('confirm').mockRejectedValueOnce('cancel')
  native.flush.mockImplementationOnce(async () => {
    useMqttStore().connectionStates.set(42, { status: 'connecting', capabilities: [] })
  })
  expect(await updater.install()).toBe(false)
  expect(native.confirm).toHaveBeenCalledTimes(3)
  expect(native.install).not.toHaveBeenCalled()
  expect(updater.canInstall).toBe(true)
})

it('retains a downloaded update after failed recheck and retries installation without downloading again', async () => {
  native.check.mockResolvedValueOnce({ version: '1.9.0', download: native.download, install: native.install, close: native.close })
  const updater = useUpdaterStore()
  await updater.check()
  await updater.download()
  native.check.mockRejectedValueOnce(new Error('offline'))
  await expect(updater.check({ interactive: true })).rejects.toThrow('offline')
  expect(updater.info?.latestVersion).toBe('v1.9.0')
  expect(updater.canInstall).toBe(true)
  native.confirm.mockResolvedValue('confirm')
  native.install.mockRejectedValueOnce(new Error('installer busy'))
  await expect(updater.install()).rejects.toThrow('installer busy')
  expect(await updater.install()).toBe(true)
  expect(native.download).toHaveBeenCalledTimes(1)
  expect(native.install).toHaveBeenCalledTimes(2)
})

it('releases a new object when replacement cannot close the old object, retaining consistent retryable metadata', async () => {
  native.check.mockResolvedValueOnce({ version: '1.9.0', download: native.download, close: native.close })
  const updater = useUpdaterStore()
  updater.setPreferences({ autoCheck: true, autoDownload: false })
  await updater.check()
  const closeNew = vi.fn().mockResolvedValue(undefined)
  native.close.mockRejectedValueOnce(new Error('resource busy'))
  native.check.mockResolvedValueOnce({ version: '2.0.0', download: vi.fn(), close: closeNew })
  await expect(updater.check({ interactive: true })).rejects.toThrow('resource busy')
  expect(updater.info?.latestVersion).toBe('v1.9.0')
  expect(updater.canDownload).toBe(true)
  expect(closeNew).toHaveBeenCalledOnce()
  await updater.dispose()
  expect(native.close).toHaveBeenCalledTimes(2)
})

it('rechecks protection in the final microtask before calling native install', async () => {
  native.check.mockResolvedValueOnce({ version: '1.9.0', download: native.download, install: native.install, close: native.close })
  const updater = useUpdaterStore()
  await updater.check()
  await updater.download()
  native.confirm.mockResolvedValueOnce('confirm').mockRejectedValueOnce('cancel')
  native.flush.mockImplementationOnce(() => ({ then(resolve: () => void) {
    resolve()
    queueMicrotask(() => useMqttStore().connectionStates.set(55, { status: 'connected', capabilities: [] }))
  } }))
  expect(await updater.install()).toBe(false)
  expect(native.install).not.toHaveBeenCalled()
})

it('retries resource cleanup on dispose after a failed skip close', async () => {
  native.check.mockResolvedValueOnce({ version: '1.9.0', download: native.download, close: native.close })
  const updater = useUpdaterStore()
  updater.setPreferences({ autoCheck: true, autoDownload: false })
  await updater.check()
  native.close.mockRejectedValueOnce(new Error('close failed'))
  await expect(updater.skipVersion()).rejects.toThrow('close failed')
  await updater.dispose()
  expect(native.close).toHaveBeenCalledTimes(2)
})

it.each(['invalid', '-20', 'Infinity', '9999999999999999'])('recovers malformed or future persisted timestamps (%s), and manual checks bypass the throttle', async timestamp => {
  localStorage.setItem('mqtt-client-update-last-checked-at', timestamp)
  localStorage.setItem('mqtt-client-update-auto-check', 'garbage')
  const updater = useUpdaterStore()
  await updater.check()
  await updater.check()
  expect(native.check).toHaveBeenCalledTimes(1)
  await updater.check({ interactive: true })
  expect(native.check).toHaveBeenCalledTimes(2)
  expect(native.check).toHaveBeenCalledWith({ timeout: 30000 })
})

it('explicitly closes a check result that arrives after disposal without reviving metadata', async () => {
  let finish!: (value: unknown) => void
  native.check.mockReturnValueOnce(new Promise(resolve => { finish = resolve }))
  const updater = useUpdaterStore()
  const checking = updater.check()
  await Promise.resolve()
  const disposing = updater.dispose()
  finish({ version: '1.9.0', close: native.close })
  await Promise.all([checking, disposing])
  expect(updater.info).toBeNull()
  expect(updater.phase).toBe('idle')
  expect(native.close).toHaveBeenCalledOnce()
  expect(native.download).not.toHaveBeenCalled()
})

it('revalidates running tasks and draft revisions after asynchronous consent and before relaunch', async () => {
  native.check.mockResolvedValueOnce({ version: '1.9.0', download: native.download, install: native.install, close: native.close })
  const updater = useUpdaterStore()
  await updater.check()
  await updater.download()
  const scope = effectScope()
  const running = ref(false)
  const draft = ref('first')
  scope.run(() => {
    useUpdateProtection('scheduled', () => running.value ? 'running' : false)
    useUpdateProtection('timed', () => running.value ? 'running' : false)
    useUpdateProtection('publish', () => draft.value)
  })
  native.confirm.mockImplementationOnce(async () => { running.value = true })
    .mockResolvedValueOnce('confirm').mockRejectedValueOnce('cancel')
  native.install.mockImplementationOnce(async () => { draft.value = 'changed after install' })
  expect(await updater.install()).toBe(false)
  expect(native.confirm).toHaveBeenCalledTimes(3)
  expect(native.install).toHaveBeenCalledOnce()
  expect(native.relaunch).not.toHaveBeenCalled()
  scope.stop()
})

it('shares installation completion while one user confirmation is pending', async () => {
  native.check.mockResolvedValueOnce({ version: '1.9.0', download: native.download, install: native.install, close: native.close })
  const updater = useUpdaterStore()
  await updater.check()
  await updater.download()
  let approve!: () => void
  native.confirm.mockReturnValueOnce(new Promise<void>(resolve => { approve = resolve }))
  const one = updater.install()
  const two = updater.install()
  approve()
  expect(await Promise.all([one, two])).toEqual([true, true])
  expect(native.confirm).toHaveBeenCalledOnce()
  expect(native.install).toHaveBeenCalledOnce()
  expect(native.relaunch).toHaveBeenCalledOnce()
})

it('reports a joined manual download failure even when the download began automatically', async () => {
  let reject!: (error: Error) => void
  native.check.mockResolvedValueOnce({ version: '1.9.0', download: native.download, close: native.close })
  native.download.mockReturnValueOnce(new Promise<void>((_, no) => { reject = no }))
  const updater = useUpdaterStore()
  await updater.check()
  const manual = updater.download()
  reject(new Error('download offline'))
  expect(await manual).toBe(false)
  expect(updater.errorVisible).toBe(true)
  expect(native.message).toHaveBeenCalledWith(expect.stringContaining('download offline'))
})

it('cannot revive an update skipped while a replacement awaits native close', async () => {
  native.check.mockResolvedValueOnce({ version: '1.9.0', download: native.download, close: native.close })
  const updater = useUpdaterStore()
  updater.setPreferences({ autoCheck: true, autoDownload: false })
  await updater.check()
  let finish!: () => void
  native.close.mockReturnValueOnce(new Promise<void>(resolve => { finish = resolve }))
  const closeNew = vi.fn().mockResolvedValue(undefined)
  native.check.mockResolvedValueOnce({ version: '2.0.0', close: closeNew })
  const rechecking = updater.check({ interactive: true })
  await Promise.resolve()
  await Promise.resolve()
  const skipping = updater.skipVersion()
  finish()
  await Promise.all([rechecking, skipping])
  expect(updater.info).toBeNull()
  expect(updater.phase).toBe('idle')
  expect(closeNew).toHaveBeenCalledOnce()
})

it('retries a failed download with its retained resource and applies the native download timeout', async () => {
  native.check.mockResolvedValueOnce({ version: '1.9.0', download: native.download, close: native.close })
  const updater = useUpdaterStore()
  updater.setPreferences({ autoCheck: true, autoDownload: false })
  await updater.check()
  native.download.mockRejectedValueOnce(new Error('timeout'))
  expect(await updater.download()).toBe(false)
  expect(updater.canDownload).toBe(true)
  expect(updater.info?.latestVersion).toBe('v1.9.0')
  expect(await updater.download()).toBe(true)
  expect(updater.canInstall).toBe(true)
  expect(native.download).toHaveBeenLastCalledWith(expect.any(Function), { timeout: 300000 })
})

it('retries relaunch after a post-install failure without installing twice', async () => {
  native.check.mockResolvedValueOnce({ version: '1.9.0', download: native.download, install: native.install, close: native.close })
  const updater = useUpdaterStore()
  await updater.check()
  await updater.download()
  native.confirm.mockResolvedValue('confirm')
  native.flush.mockResolvedValueOnce(undefined).mockRejectedValueOnce(new Error('disk full'))
  await expect(updater.install()).rejects.toThrow('disk full')
  expect(await updater.install()).toBe(true)
  expect(native.install).toHaveBeenCalledOnce()
  expect(native.relaunch).toHaveBeenCalledOnce()
})
